
#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
description = "This is meta description"
author = "BoycottBeacon"
# contact info
address = ""
mobile = ""
email = ""
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "" # your id
# top header
top_header = true

############################# Build ##############################
[build]
noJSConfigInAssets = false
useResourceCacheWhen = 'fallback'
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/.*\.(js|ts|jsx|tsx)'
target = '(js|scripts|javascript)'
[[build.cachebusters]]
source = 'assets/.*\.(css|sass|scss)$'
target = '(css|styles|scss|sass)'
[[build.cachebusters]]
source = 'assets/.*\.(.*)$'
target = '$1'


############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS"]

############################# Imaging ##############################
[imaging]
# See https://github.com/disintegration/imaging
# Default JPEG or WebP quality setting. Default is 75.
quality = 90
resampleFilter = "lanczos"

############################# Caches ###############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"

############################# Markup ###############################
[markup]
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" # Example CDN link, check for latest version

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
# JS Plugins
[[params.plugins.js]]
link = "plugins/popper/popper.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.bundle.min.js"
[[params.plugins.js]]
link = "plugins/js-cookie/js.cookie.min.js" # If you store it locally
# cookies
[params.cookies]
enable = true
expire_days = 14


############################# social site ########################
[[params.social]]
title = "github"
icon = "fa-brands fa-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/boycott-beacon/"
[[params.social]]
title = "X"
icon = "fa-brands fa-x-twitter" # themify icon : https://themify.me/themify-icons
link = "https://x.com/boycottbeacon/"

